name: Webpack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run build
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist
          git commit -m "[skip ci] updating distribution"
          git push
